@token = "Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo0LCJleHAiOjE2NjkxMjUyNjZ9.RuvohP1rQuWosbwS1Z4q0q38yGVmEb6yMpw5N35BN8k"

## Get workouts
GET http://localhost:3000/api/workouts
Authorization: "{{token}}"

### Successfully create a workout
POST http://localhost:3000/api/workouts
Authorization: "{{token}}"
Content-Type: application/json

{
    "category_id": 1,
    "description": "Bench",
    "time": "60",
    "avg_bpm": "120",
    "date": "2022-11-16"
}

### Fail to create a workout
POST http://localhost:3000/api/workouts
Content-Type: application/json

{
    "description": "Running again"
}

### Successfully show workout
GET http://localhost:3000/api/workouts/12
Authorization: "{{token}}"

### Fail to show workout
GET http://localhost:3000/api/workouts/999
Authorization: "{{token}}"

### Successfully update a workout
PUT http://localhost:3000/api/workouts/1
Content-Type: application/json
Authorization: "{{token}}"

{
    "category_id": 3,
    "description": "updated Running again"
}

### Successfully delete workout
DELETE http://localhost:3000/api/workouts/2
Authorization: "{{token}}"

### Workout based on category
GET http://localhost:3000/api/workouts/?category=swimming
Authorization: "{{token}}"

### Create a user
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "Steve33",
    "username": "Steve33",
    "email": "steve33@test.com",
    "password": "password",
    "password_confirmation": "password"
}

### Login a user
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "steve33@test.com",
    "password": "password"
}

### Fail to login a user without password
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "steve32@test.com"
}

### Get a user
GET http://localhost:3000/api/users/Steve3
Authorization: "{{token}}"

### Get all users
GET http://localhost:3000/api/users
Authorization: "{{token}}"

### Get ladder for workouts
GET http://localhost:3000/api/ladder

### Get ladder for weight
GET http://localhost:3000/api/ladder/weight

### Get ladder for swimming
GET http://localhost:3000/api/ladder/swimming

### Get ladder for running
GET http://localhost:3000/api/ladder/running